apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: wanguir/yolo-frontend:v1.0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5" 
            memory: "512Mi" 
          requests:
            cpu: "0.2" 
            memory: "256Mi" 
