version: '3'
services:
  frontend:
    build:
      context: ./client
    image: yolo-frontend-app:v1.0 
    ports:
      - '8081:80'
    depends_on:
      - backend
    networks:
      - mynetwork
  backend:
    build:
      context: ./backend
    image: yolo-backend-app:v2.0 
    ports:
      - '3001:3000'
    environment:
      - .env
    networks:
      - mynetwork
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
