version: '3'
services:
  frontend:
    build:
      context: ./client
    image: yolo-frontend-app:v1.0
    ports:
      - '8888:80'
    depends_on:
      - backend
    networks:
      - mynetwork
    command: ["tail", "-f", "/dev/null"]
  backend:
    build:
      context: ./backend
    image: yolo-backend-app:v2.0.2
    ports:
      - '3001:3000'
    environment:
      - .env
    networks:
      - mynetwork
  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
networks:
  mynetwork:
    driver: bridge

