apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend 
  ports:
    - protocol: TCP
      port: 8080 # Port on the Service
      targetPort: 8080 # Port on the Pod
  type: ClusterIP # Expose the Service inside the cluster
