apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: wanguir/yolo-frontend:v1.0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1" 
            memory: "1Gi" 
          requests:
            cpu: "1" 
            memory: "500Mi" 
